'use strict';

//chrome.runtime.onInstalled.addListener(details => {
//  console.log('previousVersion', details.previousVersion);
//});




let targetTimeZone = moment.tz.guess();
let sourceTimezone = moment.tz.guess();
console.info(`Browser timezone is ${targetTimeZone}`);

updateTimezoneOnBadge(moment().tz(targetTimeZone).format('Z z'));

function updateTimezoneOnBadge(timezone) {
  chrome.browserAction.setBadgeText({text: timezone.replace('+0','+')});
}

function genericOnClick(info, tab) {
  console.log('item ' + info.menuItemId + ' was clicked');
  console.log('info: ' + JSON.stringify(info));
  console.log('tab: ' + JSON.stringify(tab));
}4

function showConvertedTime(timeOnPage) {
  try {
    chrome.contextMenus.update(Convert_Time_Menu, {
      title: timeMenu(sourceTimezone, targetTimeZone)
    });

    updateTimezoneOnBadge(moment().tz(targetTimeZone).format('Z z'));

    const timeOnPageMoment = validateTime(timeOnPage);
    const formatedTime = moment.tz(timeOnPage, possibleFormats, sourceTimezone).tz(targetTimeZone);
    console.log(timeOnPage, formatedTime.format('lll'));
    alert(`
${timeOnPage} ===> (${timeOnPageMoment.format('lll')})
${sourceTimezone} ===> ${targetTimeZone}
------------------------------------
${formatedTime.format('lll')}  (${formatedTime.fromNow()})
`
    );

  } catch (e) {
    alert('Selected time can not be parse as time.');
  }
}


function validateTime(timeString) {
  if (moment(timeString, possibleFormats).isValid()) {
    return moment(timeString, possibleFormats);
  } else if (moment(timeString).isValid()) {
    return moment(timeString);
  } else {
    throw new Error('Invalid Time');
  }
}

const possibleFormats = [
  'MM-DD-YYYY', 'YYYY-MM-DD',
  'h:m a', 'H:m'
];

const Current_TimeZone_Menu = chrome.contextMenus.create({
  title: `Target timezone : ${targetTimeZone}`,
  contexts: ['selection'],
  enabled: false
});

const timeMenu = (currentTimezone, targetTimezone) => `Convert time ${currentTimezone} ==> ${targetTimezone}`

const Convert_Time_Menu = chrome.contextMenus.create({
  title: timeMenu(sourceTimezone, targetTimeZone),
  contexts: ['selection'],
  enabled: true,
  onclick: ({selectionText}) => showConvertedTime(
    selectionText
  )
});

const Set_Source_TimeZone_Menu = chrome.contextMenus.create({
  title: `Set Source Timezone`,
  contexts: ['selection'],
  enabled: true
});

const Set_Target_TimeZone_Menu = chrome.contextMenus.create({
  title: `Set Target Timezone`,
  contexts: ['selection'],
  enabled: true
});

const timezones = [
  'Africa/Abidjan|Africa/Bamako',
  'Africa/Abidjan|Africa/Banjul',
  'Africa/Abidjan|Africa/Conakry',
  'Africa/Abidjan|Africa/Dakar',
  'Africa/Abidjan|Africa/Freetown',
  'Africa/Abidjan|Africa/Lome',
  'Africa/Abidjan|Africa/Nouakchott',
  'Africa/Abidjan|Africa/Ouagadougou',
  'Africa/Abidjan|Africa/Sao_Tome',
  'Africa/Abidjan|Africa/Timbuktu',
  'Africa/Abidjan|Atlantic/St_Helena',
  'Africa/Cairo|Egypt',
  'Africa/Johannesburg|Africa/Maseru',
  'Africa/Johannesburg|Africa/Mbabane',
  'Africa/Khartoum|Africa/Juba',
  'Africa/Lagos|Africa/Bangui',
  'Africa/Lagos|Africa/Brazzaville',
  'Africa/Lagos|Africa/Douala',
  'Africa/Lagos|Africa/Kinshasa',
  'Africa/Lagos|Africa/Libreville',
  'Africa/Lagos|Africa/Luanda',
  'Africa/Lagos|Africa/Malabo',
  'Africa/Lagos|Africa/Niamey',
  'Africa/Lagos|Africa/Porto-Novo',
  'Africa/Maputo|Africa/Blantyre',
  'Africa/Maputo|Africa/Bujumbura',
  'Africa/Maputo|Africa/Gaborone',
  'Africa/Maputo|Africa/Harare',
  'Africa/Maputo|Africa/Kigali',
  'Africa/Maputo|Africa/Lubumbashi',
  'Africa/Maputo|Africa/Lusaka',
  'Africa/Nairobi|Africa/Addis_Ababa',
  'Africa/Nairobi|Africa/Asmara',
  'Africa/Nairobi|Africa/Asmera',
  'Africa/Nairobi|Africa/Dar_es_Salaam',
  'Africa/Nairobi|Africa/Djibouti',
  'Africa/Nairobi|Africa/Kampala',
  'Africa/Nairobi|Africa/Mogadishu',
  'Africa/Nairobi|Indian/Antananarivo',
  'Africa/Nairobi|Indian/Comoro',
  'Africa/Nairobi|Indian/Mayotte',
  'Africa/Tripoli|Libya',
  'America/Adak|America/Atka',
  'America/Adak|US/Aleutian',
  'America/Anchorage|US/Alaska',
  'America/Argentina/Buenos_Aires|America/Buenos_Aires',
  'America/Argentina/Catamarca|America/Argentina/ComodRivadavia',
  'America/Argentina/Catamarca|America/Catamarca',
  'America/Argentina/Cordoba|America/Cordoba',
  'America/Argentina/Cordoba|America/Rosario',
  'America/Argentina/Jujuy|America/Jujuy',
  'America/Argentina/Mendoza|America/Mendoza',
  'America/Atikokan|America/Coral_Harbour',
  'America/Chicago|US/Central',
  'America/Curacao|America/Aruba',
  'America/Curacao|America/Kralendijk',
  'America/Curacao|America/Lower_Princes',
  'America/Denver|America/Shiprock',
  'America/Denver|Navajo',
  'America/Denver|US/Mountain',
  'America/Detroit|US/Michigan',
  'America/Edmonton|Canada/Mountain',
  'America/Fort_Wayne|America/Indiana/Indianapolis',
  'America/Fort_Wayne|America/Indianapolis',
  'America/Fort_Wayne|US/East-Indiana',
  'America/Halifax|Canada/Atlantic',
  'America/Havana|Cuba',
  'America/Indiana/Knox|America/Knox_IN',
  'America/Indiana/Knox|US/Indiana-Starke',
  'America/Jamaica|Jamaica',
  'America/Kentucky/Louisville|America/Louisville',
  'America/Los_Angeles|US/Pacific',
  'America/Los_Angeles|US/Pacific-New',
  'America/Manaus|Brazil/West',
  'America/Mazatlan|Mexico/BajaSur',
  'America/Mexico_City|Mexico/General',
  'America/New_York|US/Eastern',
  'America/Noronha|Brazil/DeNoronha',
  'America/Panama|America/Cayman',
  'America/Phoenix|US/Arizona',
  'America/Port_of_Spain|America/Anguilla',
  'America/Port_of_Spain|America/Antigua',
  'America/Port_of_Spain|America/Dominica',
  'America/Port_of_Spain|America/Grenada',
  'America/Port_of_Spain|America/Guadeloupe',
  'America/Port_of_Spain|America/Marigot',
  'America/Port_of_Spain|America/Montserrat',
  'America/Port_of_Spain|America/St_Barthelemy',
  'America/Port_of_Spain|America/St_Kitts',
  'America/Port_of_Spain|America/St_Lucia',
  'America/Port_of_Spain|America/St_Thomas',
  'America/Port_of_Spain|America/St_Vincent',
  'America/Port_of_Spain|America/Tortola',
  'America/Port_of_Spain|America/Virgin',
  'America/Regina|Canada/East-Saskatchewan',
  'America/Regina|Canada/Saskatchewan',
  'America/Rio_Branco|America/Porto_Acre',
  'America/Rio_Branco|Brazil/Acre',
  'America/Santiago|Chile/Continental',
  'America/Sao_Paulo|Brazil/East',
  'America/St_Johns|Canada/Newfoundland',
  'America/Tijuana|America/Ensenada',
  'America/Tijuana|America/Santa_Isabel',
  'America/Tijuana|Mexico/BajaNorte',
  'America/Toronto|America/Montreal',
  'America/Toronto|Canada/Eastern',
  'America/Vancouver|Canada/Pacific',
  'America/Whitehorse|Canada/Yukon',
  'America/Winnipeg|Canada/Central',
  'Asia/Ashgabat|Asia/Ashkhabad',
  'Asia/Bangkok|Asia/Phnom_Penh',
  'Asia/Bangkok|Asia/Vientiane',
  'Asia/Dhaka|Asia/Dacca',
  'Asia/Dubai|Asia/Muscat',
  'Asia/Ho_Chi_Minh|Asia/Saigon',
  'Asia/Hong_Kong|Hongkong',
  'Asia/Jerusalem|Asia/Tel_Aviv',
  'Asia/Jerusalem|Israel',
  'Asia/Kathmandu|Asia/Katmandu',
  'Asia/Kolkata|Asia/Calcutta',
  'Asia/Macau|Asia/Macao',
  'Asia/Makassar|Asia/Ujung_Pandang',
  'Asia/Nicosia|Europe/Nicosia',
  'Asia/Qatar|Asia/Bahrain',
  'Asia/Riyadh|Asia/Aden',
  'Asia/Riyadh|Asia/Kuwait',
  'Asia/Seoul|ROK',
  'Asia/Shanghai|Asia/Chongqing',
  'Asia/Shanghai|Asia/Chungking',
  'Asia/Shanghai|Asia/Harbin',
  'Asia/Shanghai|PRC',
  'Asia/Singapore|Singapore',
  'Asia/Taipei|ROC',
  'Asia/Tehran|Iran',
  'Asia/Thimphu|Asia/Thimbu',
  'Asia/Tokyo|Japan',
  'Asia/Ulaanbaatar|Asia/Ulan_Bator',
  'Asia/Urumqi|Asia/Kashgar',
  'Atlantic/Faroe|Atlantic/Faeroe',
  'Atlantic/Reykjavik|Iceland',
  'Australia/Adelaide|Australia/South',
  'Australia/Brisbane|Australia/Queensland',
  'Australia/Broken_Hill|Australia/Yancowinna',
  'Australia/Darwin|Australia/North',
  'Australia/Hobart|Australia/Tasmania',
  'Australia/Lord_Howe|Australia/LHI',
  'Australia/Melbourne|Australia/Victoria',
  'Australia/Perth|Australia/West',
  'Australia/Sydney|Australia/ACT',
  'Australia/Sydney|Australia/Canberra',
  'Australia/Sydney|Australia/NSW',
  'Etc/GMT+0|Etc/GMT',
  'Etc/GMT+0|Etc/GMT-0',
  'Etc/GMT+0|Etc/GMT0',
  'Etc/GMT+0|Etc/Greenwich',
  'Etc/GMT+0|GMT',
  'Etc/GMT+0|GMT+0',
  'Etc/GMT+0|GMT-0',
  'Etc/GMT+0|GMT0',
  'Etc/GMT+0|Greenwich',
  'Etc/UCT|UCT',
  'Etc/UTC|Etc/Universal',
  'Etc/UTC|Etc/Zulu',
  'Etc/UTC|UTC',
  'Etc/UTC|Universal',
  'Etc/UTC|Zulu',
  'Europe/Belgrade|Europe/Ljubljana',
  'Europe/Belgrade|Europe/Podgorica',
  'Europe/Belgrade|Europe/Sarajevo',
  'Europe/Belgrade|Europe/Skopje',
  'Europe/Belgrade|Europe/Zagreb',
  'Europe/Chisinau|Europe/Tiraspol',
  'Europe/Dublin|Eire',
  'Europe/Helsinki|Europe/Mariehamn',
  'Europe/Istanbul|Asia/Istanbul',
  'Europe/Istanbul|Turkey',
  'Europe/Lisbon|Portugal',
  'Europe/London|Europe/Belfast',
  'Europe/London|Europe/Guernsey',
  'Europe/London|Europe/Isle_of_Man',
  'Europe/London|Europe/Jersey',
  'Europe/London|GB',
  'Europe/London|GB-Eire',
  'Europe/Moscow|W-SU',
  'Europe/Oslo|Arctic/Longyearbyen',
  'Europe/Oslo|Atlantic/Jan_Mayen',
  'Europe/Prague|Europe/Bratislava',
  'Europe/Rome|Europe/San_Marino',
  'Europe/Rome|Europe/Vatican',
  'Europe/Warsaw|Poland',
  'Europe/Zurich|Europe/Busingen',
  'Europe/Zurich|Europe/Vaduz',
  'Pacific/Auckland|Antarctica/McMurdo',
  'Pacific/Auckland|Antarctica/South_Pole',
  'Pacific/Auckland|NZ',
  'Pacific/Chatham|NZ-CHAT',
  'Pacific/Chuuk|Pacific/Truk',
  'Pacific/Chuuk|Pacific/Yap',
  'Pacific/Easter|Chile/EasterIsland',
  'Pacific/Guam|Pacific/Saipan',
  'Pacific/Honolulu|Pacific/Johnston',
  'Pacific/Honolulu|US/Hawaii',
  'Pacific/Kwajalein|Kwajalein',
  'Pacific/Pago_Pago|Pacific/Midway',
  'Pacific/Pago_Pago|Pacific/Samoa',
  'Pacific/Pago_Pago|US/Samoa',
  'Pacific/Pohnpei|Pacific/Ponape',
  'Africa/Abidjan',
  'Africa/Accra',
  'Africa/Nairobi',
  'Africa/Algiers',
  'Africa/Lagos',
  'Africa/Bissau',
  'Africa/Maputo',
  'Africa/Cairo',
  'Africa/Casablanca',
  'Africa/Ceuta',
  'Africa/El_Aaiun',
  'Africa/Johannesburg',
  'Africa/Khartoum',
  'Africa/Monrovia',
  'Africa/Ndjamena',
  'Africa/Tripoli',
  'Africa/Tunis',
  'Africa/Windhoek',
  'America/Adak',
  'America/Anchorage',
  'America/Port_of_Spain',
  'America/Araguaina',
  'America/Argentina/Buenos_Aires',
  'America/Argentina/Catamarca',
  'America/Argentina/Cordoba',
  'America/Argentina/Jujuy',
  'America/Argentina/La_Rioja',
  'America/Argentina/Mendoza',
  'America/Argentina/Rio_Gallegos',
  'America/Argentina/Salta',
  'America/Argentina/San_Juan',
  'America/Argentina/San_Luis',
  'America/Argentina/Tucuman',
  'America/Argentina/Ushuaia',
  'America/Curacao',
  'America/Asuncion',
  'America/Atikokan',
  'America/Bahia',
  'America/Bahia_Banderas',
  'America/Barbados',
  'America/Belem',
  'America/Belize',
  'America/Blanc-Sablon',
  'America/Boa_Vista',
  'America/Bogota',
  'America/Boise',
  'America/Cambridge_Bay',
  'America/Campo_Grande',
  'America/Cancun',
  'America/Caracas',
  'America/Cayenne',
  'America/Panama',
  'America/Chicago',
  'America/Chihuahua',
  'America/Costa_Rica',
  'America/Creston',
  'America/Cuiaba',
  'America/Danmarkshavn',
  'America/Dawson',
  'America/Dawson_Creek',
  'America/Denver',
  'America/Detroit',
  'America/Edmonton',
  'America/Eirunepe',
  'America/El_Salvador',
  'America/Tijuana',
  'America/Fort_Nelson',
  'America/Fort_Wayne',
  'America/Fortaleza',
  'America/Glace_Bay',
  'America/Godthab',
  'America/Goose_Bay',
  'America/Grand_Turk',
  'America/Guatemala',
  'America/Guayaquil',
  'America/Guyana',
  'America/Halifax',
  'America/Havana',
  'America/Hermosillo',
  'America/Indiana/Knox',
  'America/Indiana/Marengo',
  'America/Indiana/Petersburg',
  'America/Indiana/Tell_City',
  'America/Indiana/Vevay',
  'America/Indiana/Vincennes',
  'America/Indiana/Winamac',
  'America/Inuvik',
  'America/Iqaluit',
  'America/Jamaica',
  'America/Juneau',
  'America/Kentucky/Louisville',
  'America/Kentucky/Monticello',
  'America/La_Paz',
  'America/Lima',
  'America/Los_Angeles',
  'America/Maceio',
  'America/Managua',
  'America/Manaus',
  'America/Martinique',
  'America/Matamoros',
  'America/Mazatlan',
  'America/Menominee',
  'America/Merida',
  'America/Metlakatla',
  'America/Mexico_City',
  'America/Miquelon',
  'America/Moncton',
  'America/Monterrey',
  'America/Montevideo',
  'America/Toronto',
  'America/Nassau',
  'America/New_York',
  'America/Nipigon',
  'America/Nome',
  'America/Noronha',
  'America/North_Dakota/Beulah',
  'America/North_Dakota/Center',
  'America/North_Dakota/New_Salem',
  'America/Ojinaga',
  'America/Pangnirtung',
  'America/Paramaribo',
  'America/Phoenix',
  'America/Port-au-Prince',
  'America/Rio_Branco',
  'America/Porto_Velho',
  'America/Puerto_Rico',
  'America/Rainy_River',
  'America/Rankin_Inlet',
  'America/Recife',
  'America/Regina',
  'America/Resolute',
  'America/Santarem',
  'America/Santiago',
  'America/Santo_Domingo',
  'America/Sao_Paulo',
  'America/Scoresbysund',
  'America/Sitka',
  'America/St_Johns',
  'America/Swift_Current',
  'America/Tegucigalpa',
  'America/Thule',
  'America/Thunder_Bay',
  'America/Vancouver',
  'America/Whitehorse',
  'America/Winnipeg',
  'America/Yakutat',
  'America/Yellowknife',
  'Antarctica/Casey',
  'Antarctica/Davis',
  'Antarctica/DumontDUrville',
  'Antarctica/Macquarie',
  'Antarctica/Mawson',
  'Pacific/Auckland',
  'Antarctica/Palmer',
  'Antarctica/Rothera',
  'Antarctica/Syowa',
  'Antarctica/Troll',
  'Antarctica/Vostok',
  'Europe/Oslo',
  'Asia/Riyadh',
  'Asia/Almaty',
  'Asia/Amman',
  'Asia/Anadyr',
  'Asia/Aqtau',
  'Asia/Aqtobe',
  'Asia/Ashgabat',
  'Asia/Baghdad',
  'Asia/Qatar',
  'Asia/Baku',
  'Asia/Bangkok',
  'Asia/Barnaul',
  'Asia/Beirut',
  'Asia/Bishkek',
  'Asia/Brunei',
  'Asia/Kolkata',
  'Asia/Chita',
  'Asia/Choibalsan',
  'Asia/Shanghai',
  'Asia/Colombo',
  'Asia/Dhaka',
  'Asia/Damascus',
  'Asia/Dili',
  'Asia/Dubai',
  'Asia/Dushanbe',
  'Asia/Gaza',
  'Asia/Hebron',
  'Asia/Ho_Chi_Minh',
  'Asia/Hong_Kong',
  'Asia/Hovd',
  'Asia/Irkutsk',
  'Europe/Istanbul',
  'Asia/Jakarta',
  'Asia/Jayapura',
  'Asia/Jerusalem',
  'Asia/Kabul',
  'Asia/Kamchatka',
  'Asia/Karachi',
  'Asia/Urumqi',
  'Asia/Kathmandu',
  'Asia/Khandyga',
  'Asia/Krasnoyarsk',
  'Asia/Kuala_Lumpur',
  'Asia/Kuching',
  'Asia/Macau',
  'Asia/Magadan',
  'Asia/Makassar',
  'Asia/Manila',
  'Asia/Nicosia',
  'Asia/Novokuznetsk',
  'Asia/Novosibirsk',
  'Asia/Omsk',
  'Asia/Oral',
  'Asia/Pontianak',
  'Asia/Pyongyang',
  'Asia/Qyzylorda',
  'Asia/Rangoon',
  'Asia/Sakhalin',
  'Asia/Samarkand',
  'Asia/Seoul',
  'Asia/Singapore',
  'Asia/Srednekolymsk',
  'Asia/Taipei',
  'Asia/Tashkent',
  'Asia/Tbilisi',
  'Asia/Tehran',
  'Asia/Thimphu',
  'Asia/Tokyo',
  'Asia/Ulaanbaatar',
  'Asia/Ust-Nera',
  'Asia/Vladivostok',
  'Asia/Yakutsk',
  'Asia/Yekaterinburg',
  'Asia/Yerevan',
  'Atlantic/Azores',
  'Atlantic/Bermuda',
  'Atlantic/Canary',
  'Atlantic/Cape_Verde',
  'Atlantic/Faroe',
  'Atlantic/Madeira',
  'Atlantic/Reykjavik',
  'Atlantic/South_Georgia',
  'Atlantic/Stanley',
  'Australia/Sydney',
  'Australia/Adelaide',
  'Australia/Brisbane',
  'Australia/Broken_Hill',
  'Australia/Currie',
  'Australia/Darwin',
  'Australia/Eucla',
  'Australia/Hobart',
  'Australia/Lord_Howe',
  'Australia/Lindeman',
  'Australia/Melbourne',
  'Australia/Perth',
  'CET',
  'CST6CDT',
  'Pacific/Easter',
  'EET',
  'EST',
  'EST5EDT',
  'Europe/Dublin',
  'Etc/GMT+0',
  'Etc/GMT+1',
  'Etc/GMT+10',
  'Etc/GMT+11',
  'Etc/GMT+12',
  'Etc/GMT+2',
  'Etc/GMT+3',
  'Etc/GMT+4',
  'Etc/GMT+5',
  'Etc/GMT+6',
  'Etc/GMT+7',
  'Etc/GMT+8',
  'Etc/GMT+9',
  'Etc/GMT-1',
  'Etc/GMT-10',
  'Etc/GMT-11',
  'Etc/GMT-12',
  'Etc/GMT-13',
  'Etc/GMT-14',
  'Etc/GMT-2',
  'Etc/GMT-3',
  'Etc/GMT-4',
  'Etc/GMT-5',
  'Etc/GMT-6',
  'Etc/GMT-7',
  'Etc/GMT-8',
  'Etc/GMT-9',
  'Etc/UCT',
  'Etc/UTC',
  'Europe/Amsterdam',
  'Europe/Andorra',
  'Europe/Astrakhan',
  'Europe/Athens',
  'Europe/London',
  'Europe/Belgrade',
  'Europe/Berlin',
  'Europe/Prague',
  'Europe/Brussels',
  'Europe/Bucharest',
  'Europe/Budapest',
  'Europe/Zurich',
  'Europe/Chisinau',
  'Europe/Copenhagen',
  'Europe/Gibraltar',
  'Europe/Helsinki',
  'Europe/Kaliningrad',
  'Europe/Kiev',
  'Europe/Lisbon',
  'Europe/Luxembourg',
  'Europe/Madrid',
  'Europe/Malta',
  'Europe/Minsk',
  'Europe/Monaco',
  'Europe/Moscow',
  'Europe/Paris',
  'Europe/Riga',
  'Europe/Rome',
  'Europe/Samara',
  'Europe/Simferopol',
  'Europe/Sofia',
  'Europe/Stockholm',
  'Europe/Tallinn',
  'Europe/Tirane',
  'Europe/Ulyanovsk',
  'Europe/Uzhgorod',
  'Europe/Vienna',
  'Europe/Vilnius',
  'Europe/Volgograd',
  'Europe/Warsaw',
  'Europe/Zaporozhye',
  'HST',
  'Indian/Chagos',
  'Indian/Christmas',
  'Indian/Cocos',
  'Indian/Kerguelen',
  'Indian/Mahe',
  'Indian/Maldives',
  'Indian/Mauritius',
  'Indian/Reunion',
  'Pacific/Kwajalein',
  'MET',
  'MST',
  'MST7MDT',
  'Pacific/Chatham',
  'PST8PDT',
  'Pacific/Apia',
  'Pacific/Bougainville',
  'Pacific/Chuuk',
  'Pacific/Efate',
  'Pacific/Enderbury',
  'Pacific/Fakaofo',
  'Pacific/Fiji',
  'Pacific/Funafuti',
  'Pacific/Galapagos',
  'Pacific/Gambier',
  'Pacific/Guadalcanal',
  'Pacific/Guam',
  'Pacific/Honolulu',
  'Pacific/Kiritimati',
  'Pacific/Kosrae',
  'Pacific/Majuro',
  'Pacific/Marquesas',
  'Pacific/Pago_Pago',
  'Pacific/Nauru',
  'Pacific/Niue',
  'Pacific/Norfolk',
  'Pacific/Noumea',
  'Pacific/Palau',
  'Pacific/Pitcairn',
  'Pacific/Pohnpei',
  'Pacific/Port_Moresby',
  'Pacific/Rarotonga',
  'Pacific/Tahiti',
  'Pacific/Tarawa',
  'Pacific/Tongatapu',
  'Pacific/Wake',
  'Pacific/Wallis',
  'WET'
];

const parents = {};
const COMMON_CATEGORY = 'Others';

_(timezones)
  .flatMap(zonemix => zonemix.split('|'))
  .sort()
  .uniq()
  .each(timezone => {
    chrome.contextMenus.create({
      title: timezone,
      enabled: true,
      contexts: ['selection'],
      type: 'radio',
      checked: timezone === sourceTimezone,
      parentId: Set_Source_TimeZone_Menu,
      onclick: ({selectionText}) => {
        sourceTimezone = timezone;
        showConvertedTime(
          selectionText
        );
      }
    });

    chrome.contextMenus.create({
      title: timezone,
      enabled: true,
      contexts: ['selection'],
      type: 'radio',
      checked: timezone === targetTimeZone,
      parentId: Set_Target_TimeZone_Menu,
      onclick: ({selectionText}) => {
        targetTimeZone = timezone;
        showConvertedTime(
          selectionText
        );
      }
    });
  });
